### ISSUE TITLE
Suppress halftitle pages in epub

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_epubmaker#10]
Suppress halftitle pages either via CSS or XSL.

**Comment by nelliemckesson** [comment]
Note the presence of the halftitle section in the epub is causing a blank page to be added to the epub file, ergo the halftitle page should be removed entirely via XSL just before the epub conversion.

**Comment by nelliemckesson** [comment]
You can do this the same way I suppressed the toc--write a small, standalone xsl that targets section[data-type="halftitlepage"], and run that within epubmaker, before the actual epub conversion.

As part of the testing process, you'll want to take a look at some converted epubs and make sure the halftitle page is completely removed from the output, that no extra blank pages have been added in its place, and that there is no link for the halftitle page in the app TOC.

**Comment by mattretzer** [comment]
added strip-halftitle.xsl file and call it in epubmaker.rb 
Tested, looks ok
