### ISSUE TITLE
Move epub copyright page to back of book

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_epubmaker#4]
Copyright page should be last file in the ebook

**Comment by nelliemckesson** [comment]
Another request by the ebooks group. This will need to happen to the HTML, before it gets run through the HTMLBook XSL in epubmaker. This is probably best accomplished via JavaScript or XSL, but if you can think of a clean way to do it via Ruby, that should be ok. The cleaner the better, though (which means it really ought to be done via a content-manipulation tool like JavaScript or XSL). You'll want to hook onto the section[data-type="copyright-page"] and move the whole thing to be the last element before the closing body tag in the html.

**Comment by mattretzer** [comment]
As per Nellie's idea, skipped the xsl. 
Did this via ruby gsub of the content.opf file, to directly re-order elements in the epub.
