### ISSUE TITLE
Update epub copyright page formatting

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_epubmaker#5]
Per Natalie: 

* Links on Copyright page s/b hyperlinked. 
* Ebook ISBNs s/b “eISBN xxxxx” as opposed to “ISBN xxxx (ebook)”
* Remove serial number from bottom of copyright, i.e. “10 9 8 7 6 5 4 3 2 1”
* Missing the “©” symbol following “Copyright” in “Copyright 2015 by Katie Lord Brown”; 
* Remove “Printed in the United States of America.”

**Comment by nelliemckesson** [comment]
These are all changes to the copyright page for the ebook only, as requested by the ebooks group.

I'm not sure what the best way to go about these changes is--either ruby, XSL, or introducing a new element to the toolchain (like JavaScript). Phase one of tackling this will be just to look at some samples and think about the best way to handle this. Except for the isbns, the paragraphs don't have unique tags to make them easy to grab, so it'll have to be content-based. Exact content may also differ depending on the book (especially for the serial number, which changes depending on the printing of the book).

**Comment by mattretzer** [comment]
Added all replacements via ruby gsubs, tested
Note 1: the weblink gsub presumes the items are not already links
Note 2: Printer's key (10 9 8 7 etc) presumes it could be the only copyright <p> with just a number, eg <p class="xxx">###</p>
